return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "stylua",
      "yaml-language-server",
      "phpcs",
      "phpactor",
      "lua-language-server",
      "blade-formatter",
      "eslint-lsp",
      "gitui",
      "intelephense",
      "json-lsp",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "php-cs-fixer",
      "prettier",
      "shellcheck",
      "shfmt",
      "tailwindcss-language-server",
      "vtsls",
      "vue-language-server",
    },
  },
}
